org: mesheo
app: webhook2drive
service: webhook2drive

frameworkVersion: '3'

custom:
  wsgi:
    app: app.app
  pythonRequirements:
    dockerizePip: non-linux

provider:
  name: aws
  runtime: python3.10

functions:
  api:
    handler: wsgi_handler.handler
    events:
      - httpApi: '*'

plugins:
  - serverless-wsgi
  - serverless-python-requirements

package:
  exclude:
    - node_modules/**
    - venv/**